tailwind.config={theme:{extend:{colors:{orange:{300:"#F5D989",400:"#EDBE5E",500:"#E8AB30",600:"#DB7706",900:"#78350F"},amber:{500:"#F59E0B",600:"#D97706"}}}},plugins:[function({addUtilities:w}){const a={},e={},r={},s=[0,5,10,15,20,30,45,75];s.forEach(t=>{a[`.rotate-x-${t}`]={"--tw-rotate-x":`${t}deg`,transform:`
            translate3d(var(--tw-translate-x, 0), var(--tw-translate-y, 0), var(--tw-translate-z, 0))
            rotateX(var(--tw-rotate-x, 0))
            rotateY(var(--tw-rotate-y, 0))
            rotateZ(var(--tw-rotate-z, 0))
            skewX(var(--tw-skew-x, 0))
            skewY(var(--tw-skew-y, 0))
            scaleX(var(--tw-scale-x, 1))
            scaleY(var(--tw-scale-y, 1))
          `.replace(/\s+/g," ").trim()},t!==0&&(a[`.-rotate-x-${t}`]={"--tw-rotate-x":`-${t}deg`,transform:`
              translate3d(var(--tw-translate-x, 0), var(--tw-translate-y, 0), var(--tw-translate-z, 0))
              rotateX(var(--tw-rotate-x, 0))
              rotateY(var(--tw-rotate-y, 0))
              rotateZ(var(--tw-rotate-z, 0))
              skewX(var(--tw-skew-x, 0))
              skewY(var(--tw-skew-y, 0))
              scaleX(var(--tw-scale-x, 1))
              scaleY(var(--tw-scale-y, 1))
            `.replace(/\s+/g," ").trim()})}),s.forEach(t=>{e[`.rotate-y-${t}`]={"--tw-rotate-y":`${t}deg`,transform:`
            translate3d(var(--tw-translate-x, 0), var(--tw-translate-y, 0), var(--tw-translate-z, 0))
            rotateX(var(--tw-rotate-x, 0))
            rotateY(var(--tw-rotate-y, 0))
            rotateZ(var(--tw-rotate-z, 0))
            skewX(var(--tw-skew-x, 0))
            skewY(var(--tw-skew-y, 0))
            scaleX(var(--tw-scale-x, 1))
            scaleY(var(--tw-scale-y, 1))
          `.replace(/\s+/g," ").trim()},t!==0&&(e[`.-rotate-y-${t}`]={"--tw-rotate-y":`-${t}deg`,transform:`
              translate3d(var(--tw-translate-x, 0), var(--tw-translate-y, 0), var(--tw-translate-z, 0))
              rotateX(var(--tw-rotate-x, 0))
              rotateY(var(--tw-rotate-y, 0))
              rotateZ(var(--tw-rotate-z, 0))
              skewX(var(--tw-skew-x, 0))
              skewY(var(--tw-skew-y, 0))
              scaleX(var(--tw-scale-x, 1))
              scaleY(var(--tw-scale-y, 1))
            `.replace(/\s+/g," ").trim()})}),s.forEach(t=>{r[`.rotate-z-${t}`]={"--tw-rotate-z":`${t}deg`,transform:`
            translate3d(var(--tw-translate-x, 0), var(--tw-translate-y, 0), var(--tw-translate-z, 0))
            rotateX(var(--tw-rotate-x, 0))
            rotateY(var(--tw-rotate-y, 0))
            rotateZ(var(--tw-rotate-z, 0))
            skewX(var(--tw-skew-x, 0))
            skewY(var(--tw-skew-y, 0))
            scaleX(var(--tw-scale-x, 1))
            scaleY(var(--tw-scale-y, 1))
          `.replace(/\s+/g," ").trim()},t!==0&&(r[`.-rotate-z-${t}`]={"--tw-rotate-z":`-${t}deg`,transform:`
              translate3d(var(--tw-translate-x, 0), var(--tw-translate-y, 0), var(--tw-translate-z, 0))
              rotateX(var(--tw-rotate-x, 0))
              rotateY(var(--tw-rotate-y, 0))
              rotateZ(var(--tw-rotate-z, 0))
              skewX(var(--tw-skew-x, 0))
              skewY(var(--tw-skew-y, 0))
              scaleX(var(--tw-scale-x, 1))
              scaleY(var(--tw-scale-y, 1))
            `.replace(/\s+/g," ").trim()})}),w({...a,...e,...r,...{".perspective-none":{perspective:"none"},".perspective-dramatic":{perspective:"100px"},".perspective-near":{perspective:"300px"},".perspective-normal":{perspective:"500px"},".perspective-midrange":{perspective:"800px"},".perspective-distant":{perspective:"1200px"}},...{".transform-style-preserve-3d":{"transform-style":"preserve-3d"},".transform-style-flat":{"transform-style":"flat"}}})}]};
